name: "latex: TZ"

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: [ 'docs/tz/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: xu-cheng/latex-action@v2
        with:
          root_file: tz.tex
          working_directory: 'docs/tz'
          latexmk_use_lualatex: true
          latexmk_shell_escape: true
          
      - uses: actions/upload-artifact@v2
        with:
          name: TZ
          path: 'docs/tz/tz.pdf'
